name: jobpilotai
description: L'assistant IA pour les artisans africains.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Services Backend & Firebase
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  http: ^1.2.1

  # Utilitaires
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  open_file: ^3.3.2
  speech_to_text: ^6.6.2
  universal_html: ^2.2.4
  uuid: ^4.4.0 # Pour les IDs de messages du chat
  
  # UI & Rendu
  google_fonts: ^6.2.1
  flutter_markdown: ^0.7.1 # Pour le formatage du chatbot
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Déclaration du dossier pour le logo
  assets:
    - assets/